up

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -118,4 +118,11 @@ jobs:
         timeout_minutes: 1000
         command: |
           export LD_LIBRARY_PATH="/usr/local/lib/:$LD_LIBRARY_PATH"
-          cd metagraph/build && make check
+          cd metagraph/build
+          make check || echo "TEST_FAILED" > test_failed.status
+          if [ -f test_failed.status ]; then
+            echo "Test step failed! Printing memory usage:"
+            free -h
+            cat /proc/meminfo
+            exit 1  # Fail the workflow
+          fi
